site_name: CultureLinux
site_url: https://cyklodev.github.io/culturelinux/

theme: 
  name: material
  palette:
    scheme: slate  
  #features:
  #  - navigation.tabs
  #  - navigation.tabs.sticky
  #  - navigation.indexes 
extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Linux: 
    - 'Environement' : linux/environnement.md
    - 'History' : linux/history.md
    - 'Users' : linux/users.md
    - 'Security' : linux/security.md    
    - 'Nmap' : linux/nmap.md
  - Debian: 
    - 'Network' : debian/network.md
    - 'NFTables' : debian/nftables.md    
    - 'Email' : debian/msmtp.md        
  - Databases: 
    - 'MongoDB' : databases/mongodb.md    
  - Virtualization:
    - 'Proxmox' : virtualization/proxmox.md      
  - 'Infra As Code':
    - 'OpenToFu' : iac/opentofu.md      